In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Reading the population data

In [6]:
population_data=pd.read_csv("/home/dineshkumardavanam/Downloads/Integrated Household Survey.csv")

# Reading the Water data

In [7]:
water_data=pd.read_csv("/home/dineshkumardavanam/Downloads/Water supply.csv")

In [8]:
population_data

,Districts,Households,Total Population,Scheduled Castes,% SC Population,Scheduled Tribes,% ST Populaiton,Backward Castes,% BC Population,Others,Others %,Minorities Population,Minorities Population %
0,ADILABAD,202954,743983,112912,15,250461,34,270258,36,110352,15,108281,14.554230
1,BHADRADRI,325055,1069332,159831,15,406584,38,363128,34,139789,13,79355,7.420988
2,HYDERABAD,1049686,3979372,439097,11,80025,2,1410626,35,2049624,52,1845620,46.379680
3,JAGTIAL,317981,1019045,178760,18,31073,3,683220,67,125992,12,86394,8.477938
4,JANGAON,181878,625537,138994,22,70956,11,359099,57,56488,9,27502,4.396542
5,JAYASHANKAR,231133,723299,148025,20,137348,19,369325,51,68601,9,27244,3.766630
6,JOGULAMBA,144931,667086,142721,21,12660,2,435886,65,75819,11,63786,9.561886
7,KAMAREDDY,277355,996139,166675,17,98194,10,600972,60,130298,13,109994,11.042033
8,KARIMNAGAR,318562,1029078,212327,21,14892,1,611567,59,190292,18,101359,9.849496
9,KHAMMAM,466855,1427465,309928,22,210335,15,621612,44,285590,20,121863,8.537022
10,KOMARAM BHEEM,147606,539579,86829,16,159817,30,235205,44,57728,11,49304,9.137494
11,MAHABUBABAD,251739,837365,122997,15,320532,38,330817,40,63019,8,33109,3.953951
12,MAHABUBNAGAR,354405,1588973,261676,16,156325,10,961324,60,209648,13,180649,11.368916
13,MANCHERIAL,250787,820137,213652,26,75526,9,447559,55,83400,10,55949,6.821909
14,MEDAK,219492,789074,141474,18,81586,10,493996,63,72018,9,58820,7.454307
15,MEDCHAL,768525,2802725,399054,14,79240,3,1262484,45,1061947,38,405405,14.464673
16,NAGARKURNOOL,220673,921623,207011,22,121321,13,477912,52,115379,13,57058,6.191035
17,NALGONDA,509502,1682883,321496,19,231991,14,887485,53,241911,14,112397,6.678836
18,NIRMAL,224483,751115,121522,16,99831,13,422029,56,107733,14,118776,15.813291
19,NIZAMABAD,463398,1614942,238255,15,123561,8,888288,55,364838,23,354854,21.973173
20,PEDDAPALLI,248005,785172,169023,22,18965,2,507805,65,89379,11,53528,6.817360
21,RAJANNA,177463,566897,113665,20,25715,5,356436,63,71081,13,27328,4.820629
22,RANGAREDDY,768920,2913767,449066,15,174509,6,1293320,44,996872,34,462990,15.889740
23,SANGAREDDY,425968,1569863,332913,21,105413,7,870944,55,260593,17,291411,18.562830
24,SIDDIPET,310642,1070730,206622,19,32161,3,677810,63,154137,14,67341,6.289261
25,SURYAPET,358109,1125596,229043,20,150750,13,571743,51,174060,15,81102,7.205249
26,VIKARABAD,247692,971558,205077,21,120652,12,493724,51,152105,16,140614,14.473042
27,WANAPARTHY,134579,602522,106501,18,52642,9,367565,61,75814,13,37882,6.287239
28,WARANGAL (R),233751,746710,138846,19,114829,15,428603,57,64432,9,31753,4.252387
29,WARANGAL (U),330982,1120468,226137,20,36612,3,664146,59,193573,17,144354,12.883367
30,YADADRI,232518,774509,144455,19,49947,6,476121,61,103986,13,36175,4.670701

In [9]:
water_data

,ULB name,Source of water,Water Demand (MLD),Water Treatment facility (MLD),Utilisation of treatment facility,Storage Capacity (MLD),Protected water supply reservoirs,Total installed capacity of protected water supply (MGD),House service connections (No's),Public stand posts,...,Power bores (No's),Hand bores (No's),Water Connections (No's),Residential Connections,Commercial Connections,Metered Connections,Covered Population (%),Unserved population (%),No of Hours supply in a day,Cost Recovery of Maintenance
0,Adilabad,Sathanala River & Mavala Tank,0.00,0.00,0.00,7.20,7,92,12791,200,...,7,794,11998,11980,18,0,91.0,9.0,1,100
1,Andol-Jogipet,"Etigadda,Sathyasai,Vonappuram,Borewells",2.92,0.00,0.00,3.30,1,0,1375,2,...,110,4,1375,1230,145,0,80.0,5.0,1,495000
2,Armoor,surface and ground water,7.00,11.50,5.50,3.50,1,22,10358,254,...,192,56,10358,10358,0,0,98.2,1.8,6,0
3,Atchampet,Bore wells,3.00,0.60,4.00,0.50,0,1,3450,400,...,92,56,3450,3450,0,0,90.0,10.0,0,24
4,Badangpet,HMWS&SB BORE WELLS,14.25,0.00,0.00,7.00,0,0,14020,0,...,370,30,14020,14020,0,0,54.7,45.3,1,16824000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,Vikarabad,Shivasagar Tank and HMWS,8.10,4.94,4.94,4.94,13,6,10138,0,...,74,275,10138,10130,8,0,85.0,15.0,1,0
68,Wanaparthy,Ramanpadu Balancing resorvior,12.00,8.50,0.00,0.00,0,0,8800,238,...,30,58,8820,8800,20,0,70.0,35.0,2,0
69,Warangal,NaN,0.00,0.00,0.00,0.00,0,0,0,0,...,0,0,0,0,0,0,0.0,0.0,0,0
70,Yellandu,"YELLANDULAPADU CHERUVU, KOTILINGALA BORES, 47 ...",4.72,4.50,4.50,4.50,5,1,5992,20,...,7,69,5992,5980,12,0,80.0,20.0,1,150
71,Zaheerabad,Singoor dam back canal river water at itikepal...,5.40,5.40,0.00,7.40,2,0,5324,325,...,165,0,5324,5324,0,0,92.0,8.0,45,16

# Finding the data type

In [11]:
population_data.dtypes

Districts                   object
Households                   int64
Total Population             int64
Scheduled Castes             int64
% SC Population              int64
Scheduled Tribes             int64
% ST Populaiton              int64
Backward Castes              int64
% BC Population              int64
Others                       int64
Others %                     int64
Minorities Population        int64
Minorities Population %    float64
dtype: object

In [12]:
water_data.dtypes

ULB name                                                     object
Source of water                                              object
Water Demand (MLD)                                          float64
Water Treatment facility (MLD)                              float64
Utilisation of treatment facility                           float64
Storage Capacity (MLD)                                      float64
Protected water supply reservoirs                             int64
Total installed capacity of protected water supply (MGD)      int64
House service connections (No's)                              int64
Public stand posts                                            int64
Length of distribution pipe line (Kms)                      float64
Area Covered (%)                                              int64
Water supply through bore wells (MGD)                       float64
Power bores (No's)                                            int64
Hand bores (No's)                                             int64
Water Connections (No's)                                      int64
Residential Connections                                       int64
Commercial Connections                                        int64
Metered Connections                                           int64
Covered Population (%)                                      float64
Unserved population (%)                                     float64
No of Hours supply in a day                                   int64
Cost Recovery of Maintenance                                  int64
dtype: object